#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0

WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 900
VERS_MAJ = 0
VERS_MIN = 0
VERS_PAT = 1
VERS_SUF = "-dev"
SQ_SIZE = min(WINDOW_WIDTH, WINDOW_HEIGHT) // 18
HEIGHT_DIM = WINDOW_HEIGHT // SQ_SIZE
WIDTH_DIM = WINDOW_WIDTH // SQ_SIZE
FPS = 60
SMALLER_DIM = min(WINDOW_HEIGHT, WINDOW_WIDTH)
